### ISSUE TITLE
Is this allowed by Apple?

### ISSUE THREAD

**Issue by wmertens** [reployapp/react-native-versions#6]
I thought Apple didn't allow interpreters (React Native walking a fine line there) and this project takes that one step further, changing app behavior after installation.

Just curious...

**Comment by johanneslumpe** [comment]
The AppStore guidelines permit updating content which runs in JSC. That said, updating the javascript bundle is a safe thing to do.

Obviously there are probably going to be changes to that policy as soon as people start misusing it. But for now it is fine.

**Comment by jsierles** [comment]
Plenty of frameworks already download and execute code: titanium, meteor, ionic, etc. I believe apple considers this safe because they all run in in Apple's own private JSC. That said, even apps built with a privately linked JSCore have been accepted, for example using http://impactjs.com/ejecta. The wording in the TOS suggests that apps will be rejected only if the code changes the intended and described behavior of the app.

We'll see!

**Comment by dsibiski** [comment]
Just adding this for reference:

> 3.3.2 An Application may not download or install executable code. Interpreted
code may only be used in an Application if all scripts, code and interpreters are
packaged in the Application and not downloaded. **The only exception to the
foregoing is scripts and code downloaded and run by Apple's built-in WebKit
framework or JavascriptCore**, provided that such scripts and code do not change
the primary purpose of the Application by providing features or functionality that are
inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store.

https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf

**Comment by wmertens** [comment]
¨downloaded and run by Apple¨, hmm that is a subtle difference from
¨downloaded by the app and run by Apple¨.
We'll see. On Android it is allowed for sure in any case :-)

On Mon, Aug 24, 2015, 23:26 Dave Sibiski <notifications@github.com> wrote:

> Just adding this for reference:
>
> 3.3.2 An Application may not download or install executable code.
> Interpreted
> code may only be used in an Application if all scripts, code and
> interpreters are
> packaged in the Application and not downloaded.
>
> *The only exception to the foregoing is scripts and code downloaded and
> run by Apple's built-in WebKit framework or JavascriptCore*, provided
> that such scripts and code do not change
> the primary purpose of the Application by providing features or
> functionality that are
> inconsistent with the intended and advertised purpose of the Application as
> submitted to the App Store.
>
>
> https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reployapp/react-native-versions/issues/6#issuecomment-134385142>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by johanneslumpe** [comment]
@wmertens you misread it. It does not state 
> Downloaded and run by Apple

It says 

> Downloaded and run by Apple**'s**

which makes it clear that this is referring to Apple's JSC and not "downloaded by Apple". Else the following statement wouldn't make any sense:

> provided that such scripts and code do not change
the primary purpose of the Application by providing features or functionality that are
inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store
